apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "bugbash1621-2d28"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "bugbash1621-2d28"
    spec:
      containers:
        - name: "bugbash1621-2d28"
          image: "abhisheaacr.azurecr.io/bugbash1621"
          ports:
          - containerPort: 80